name: Release

on:
  workflow_dispatch:
  push:
    tags: [v*]

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write  # Grants permission to create a release and upload assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global url."https://user:${{ secrets.GITHUB_TOKEN }}@github".insteadOf https://github
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com          

      - name: Build app and installer
        shell: PowerShell
        run: ./build.ps1

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} './Installer/vault-explorer-installer.exe' --title "${{ github.ref_name }}" --draft --latest --verify-tag --notes-from-tag

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vault-explorer-installer
          path: ./Installer/vault-explorer-installer.exe
          if-no-files-found: error
